In [8]:
from scipy.io.wavfile import write
import numpy as np

samplerate = 16000;

In [9]:
data_input = np.genfromtxt("pdm_dual.log", delimiter=',')  
print(data_input)

[[ -5252.  -2355.]
 [ -1673.   -824.]
 [  8098.  -3219.]
 ...
 [  9752.   4786.]
 [-12954.   4485.]
 [-30133.  -2164.]]


In [10]:
data_input = data_input.T
print(data_input)

[[ -5252.  -1673.   8098. ...   9752. -12954. -30133.]
 [ -2355.   -824.  -3219. ...   4786.   4485.  -2164.]]


You need to choose which type of string you received
This type 1

In [11]:
data_serial_number = data_input[0]
print(data_serial_number)
left_channel = data_input[1]
print(left_channel)
right_channel = data_input[2]
print(right_channel)

[ -5252.  -1673.   8098. ...   9752. -12954. -30133.]
[-2355.  -824. -3219. ...  4786.  4485. -2164.]


IndexError: index 2 is out of bounds for axis 0 with size 2

You need to choose which type you received
This is type 2

In [12]:
left_channel = data_input[0]
print(left_channel)
right_channel = data_input[1]
print(right_channel)

[ -5252.  -1673.   8098. ...   9752. -12954. -30133.]
[-2355.  -824. -3219. ...  4786.  4485. -2164.]


In [13]:
dual_channel = left_channel + right_channel
dual_channel = dual_channel / 2
print(dual_channel)

[ -3803.5  -1248.5   2439.5 ...   7269.   -4234.5 -16148.5]


In [14]:
write("pdm16_example.wav", samplerate, dual_channel.astype(np.int16))